services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - mynetwork
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      -  mynetwork

networks:
  mynetwork:
    driver: bridge
